



How to Create Mobile RDP || Android RDP || Mr Arif Baba
Mr Arif Baba43 viewsSep 5, 2021
Hi Guy's, Today i Tell you that how to Create  Mobile Android ISO RDP in 2021

#MobileRDP   #AndroidRDP 
#ISORDP  #MrArifBaba


This Video for educational purposes, RDP can be used to test different projects, not to abuse or initiate illegal activities !!!

Links :
https://github.com
https://ngrok.com

........................................................................

name: MrRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/rom... -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/rom... -OutFile start.bat
    - name: Extracting Ngrok Files.
      run: Expand-Archive ngrok.zip
    - name: Connecting to your Ngrok account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Activating RDP access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Creating Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Connecting to your RDP.
      run: cmd /c start.bat
    - name: RDP is ready!
      run: | 
        Invoke-WebRequest https://raw.githubusercontent.com/rom... -OutFile loop.ps1
        ./loop.ps1










